version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.5

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "package.json" }}
            - deps-
      - run:
          name: yarn-install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: deps-{{ checksum "package.json" }}
      - run:
          name: build
          command: yarn run build
      - run:
          name: cp-cname
          command: cp CNAME build/
      - run:
          name: gh-pages
          command: ./scripts/deploy-ghpages.sh build

